from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "sysplugin"))
from create3nx_common import build_module
#makepluginstart#
# generated by makeplugin.sh
plugin_defs = [
]
#makepluginend#
build_module("rosalina", 0x24584E33, plugin_defs)