from pathlib import Path
from tempfile import TemporaryDirectory
import argparse
import json
import sys

ROOT = Path(__file__).resolve().parent
SYPLUGIN_ROOT = ROOT.parents[1] / "sysplugin"
sys.path.insert(0, str(SYPLUGIN_ROOT))

from binutils_elf import read_decoded_locations, read_symbols
from semantic_marker import (
    attach_dwarf_addresses,
    load_semantic_anchors,
    marker_fingerprint,
    resolve_source_markers,
    scan_markers,
)

ELF_PATH = ROOT / f"{ROOT.name}.elf"
MANIFEST_DIR = ROOT / "build" / "semantic_markers"
OUT_PATH = ROOT / "plgmarkers.ld"
KEY_PATH = ROOT / "plgmarkers.keys"


def atomic_text(path, text):
    with TemporaryDirectory(prefix=".plgmarkers-", dir=ROOT) as temp_dir:
        temp_path = Path(temp_dir) / path.name
        temp_path.write_text(text.rstrip("\r\n"), encoding="utf-8", newline="\n")
        temp_path.replace(path)


def fingerprint():
    extras = [
        Path(__file__),
        SYPLUGIN_ROOT / "semantic_marker.py",
        SYPLUGIN_ROOT / "semantic_marker_plugin.cc",
    ]
    return marker_fingerprint(ROOT, extras)


def prepare():
    markers = scan_markers(ROOT)
    if not markers:
        atomic_text(OUT_PATH, "/* generated by gen_plgmarkers.py - no markers found */")
        atomic_text(KEY_PATH, "{}")
        print(f"{ROOT.name}: no PLG_MARKER(name) markers found")
        return
    lines = ["/* generated semantic marker placeholders */"]
    for name in sorted(markers):
        rec = markers[name]
        lines.append(
            f"PROVIDE({name} = 0x00000000); /* {rec['rel']}:{rec['line']}:{rec['col']} */"
        )
    atomic_text(OUT_PATH, "\n".join(lines))
    print(f"{ROOT.name}: prepared {len(markers)} semantic marker placeholder(s)")


def reject_symbol_collisions(markers):
    for sym in read_symbols(ELF_PATH):
        if not sym.name or sym.name not in markers:
            continue
        if sym["st_shndx"] != "SHN_ABS" or int(sym["st_value"]) != 0:
            rec = markers[sym.name]
            raise SystemExit(
                f"marker {sym.name!r} at {rec['rel']}:{rec['line']} collides with "
                f"a real symbol in {ELF_PATH.name}"
            )


def resolve():
    if not ELF_PATH.exists():
        raise SystemExit(f"missing linked module ELF: {ELF_PATH}")
    markers = scan_markers(ROOT)
    if not markers:
        atomic_text(KEY_PATH, "{}")
        print(f"{ROOT.name}: no semantic marker keys required")
        return
    reject_symbol_collisions(markers)
    anchors = load_semantic_anchors(MANIFEST_DIR, ROOT)
    resolve_source_markers(ROOT, anchors)
    attach_dwarf_addresses(anchors, read_decoded_locations(ELF_PATH), ROOT)
    resolved = resolve_source_markers(ROOT, anchors)
    key_map = {}
    for name in sorted(resolved):
        marker = resolved[name]
        anchor = marker["anchor"]
        if "address" not in anchor:
            raise SystemExit(
                f"marker {name!r} at {marker['rel']}:{marker['line']}:{marker['col']} "
                "resolved to a GCC semantic construct with no usable linked DWARF address"
            )
        if anchor["address"] & 3:
            raise SystemExit(
                f"marker {name!r} resolved to unaligned ARM address 0x{anchor['address']:08X}"
            )
        key_map[name] = {
            "key": anchor["key"],
            "kind": anchor["kind"],
            "semantic": anchor["semantic"],
            "occurrence": anchor["occurrence"],
        }
        exact = "exact" if anchor.get("dwarf_exact") else f"column {anchor.get('dwarf_column')}"
        print(
            f"{name}: {anchor['rel']}:{anchor['line']}:{anchor['col']} -> "
            f"{anchor['function']} {anchor['kind']} {anchor['semantic']} "
            f"occ={anchor['occurrence']} key=0x{anchor['key']:016X} "
            f"DWARF={exact}"
        )
    atomic_text(KEY_PATH, json.dumps(key_map, sort_keys=True, separators=(",", ":")))
    print(f"{ROOT.name}: wrote {len(key_map)} semantic marker key(s)")


def main():
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--fingerprint", action="store_true")
    mode.add_argument("--prepare", action="store_true")
    mode.add_argument("--resolve", action="store_true")
    args = parser.parse_args()
    if args.fingerprint:
        print(fingerprint())
    elif args.prepare:
        prepare()
    else:
        resolve()


if __name__ == "__main__":
    main()